### ISSUE TITLE
运行train.py时报错

### ISSUE THREAD

**Issue by dynamite1218** [linhandev/medSeg#8]
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './log/2021-06-02 19:32:33.152873'

**Comment by dynamite1218** [comment]
> OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './log/2021-06-02 19:32:33.152873'

这个暂时放过，TRAIN里没有THICKNESS，只有PREP里有，请问代码应该怎么改

**Comment by dynamite1218** [comment]
这段代码对显卡要求很高吗。我的6g显存不够用啊，batchsize=2都跑不下来是怎么回事

**Comment by dynamite1218** [comment]
跑起来了，但是跑到一半出现bug，不知道是什么原因
  logging.warn('Your reader has raised an exception!')
WARNING:root:Your reader has raised an exception!
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\wzm\.conda\envs\py3.9\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\wzm\.conda\envs\py3.9\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\paddle\fluid\reader.py", line 1295, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\paddle\fluid\reader.py", line 1275, in __thread_main__
    for tensors in self._tensor_reader():
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\paddle\fluid\data_feeder.py", line 241, in __call__
    for each_sample in self.generator():
  File "D:\paddle\medSeg-main\medseg\train.py", line 60, in reader
    imgs = data["imgs"]
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\numpy\lib\npyio.py", line 253, in __getitem__
    return format.read_array(bytes,
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\numpy\lib\format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
Traceback (most recent call last):
  File "D:\paddle\medSeg-main\medseg\train.py", line 214, in <module>
    main()
  File "D:\paddle\medSeg-main\medseg\train.py", line 156, in main
    for train_data in train_loader():
  File "C:\Users\wzm\.conda\envs\py3.9\lib\site-packages\paddle\fluid\reader.py", line 1251, in __next__
    return self._reader.read_next()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_relese\paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by linhandev** [comment]
最近在整理训练方面的代码，建议可以先转成图片试试[PaddleSeg](https://github.com/paddlepaddle/paddleseg)，效果不错，应该没什么bug
